#cloud-config

# In order to access RStudio server via the web interface, you must log on with
# a user account that allows password access. This script does not add that user
# by default. You may either ssh as root into the server and `adduser` as
# normal, or script a user addition here:

# users:
#   - name: # username #
#     lock-passwd: false # allow login with password
#     passwd: # hashed password #

# Add apt mirror to get the latest version of R necessary for Shiny
apt_sources:
  - source: deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/
    keyid: E298A3A825C0D65DFD57CBB651716619E084DAB9
package_upgrade: true
packages:
  - nginx
  - libxml2-dev
  - libcurl4-gnutls-dev
  - libssl-dev
  - r-base-dev
  - libapparmor1
  - gdebi-core
  - git-core
write_files:
  # Forward ports for Rstudio and Shiny
  - path: /etc/nginx/sites-enabled/default
    content: |
      server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        root /usr/share/nginx/html;
        index index.html index.htm;

        # Make site accessible from http://localhost/
        server_name localhost;

        location / {
          # First attempt to serve request as file, then
          # as directory, then fall back to displaying a 404.
          try_files $uri $uri/ =404;
          # Uncomment to enable naxsi on this location
          # include /etc/nginx/naxsi.rules
        }

        location /shiny/ {
          proxy_pass http://127.0.0.1:3838/;
        }

        location /rstudio/ {
          proxy_pass http://127.0.0.1:8787/;
        }
        
        location /api/ {
          proxy_pass http://127.0.0.1:8080/;
        }
        
      }
runcmd:
  # Install "shiny" package for R
  - R -e 'install.packages("shiny", repos="https://cran.rstudio.com/")'
  # Install tidyverse
  - R -e 'install.packages(c("tidyverse"), repos="https://cran.rstudio.com/")'
  # Install other R packages
  - R -e 'install.packages(c("devtools", "reshape2", "plyr", "Quandl", "data.table", "plumber"), repos="https://cran.rstudio.com/")'
  # Install misc R packages
  - R -e 'install.packages(c("forecast", "urca", "fpp"), repos="https://cran.rstudio.com/")'
  # Install more R packages
  - R -e 'install.packages(c("haven", "readr", "jsonlite"), repos="https://cran.rstudio.com/")'
  # Install more R packages
  - R -e 'install.packages(c("prettydoc", "")), repos="https://cran.rstudio.com/")'
  # Install dev packages from github
  - R -e 'devtools::install_github('andrewjdyck/statscanr')'
  
  # Install private repos from github
  # TO DO: Need to figure out how to do this safely.
  
  # Download and install rstudio-server
  - wget https://download2.rstudio.org/server/trusty/amd64/rstudio-server-1.2.5033-amd64.deb
  - gdebi -n rstudio-server-1.2.5033-amd64.deb
  # Download and install Shiny
  - wget https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.13.944-amd64.deb
  - gdebi -n shiny-server-1.5.13.944-amd64.deb
  # Install Anaconda & deep learning libraries
  #- wget https://repo.continuum.io/archive/Anaconda3-5.1.0-Linux-x86_64.sh
  #- bash ~/Anaconda3-5.1.0-Linux-x86_64.sh -b -p $HOME/anaconda
  #- export PATH="$HOME/anaconda/bin:$PATH"
  #- conda install -cy anaconda tensorflow
  #- conda install -cy conda-forge keras
  #- R -e 'install.packages(c("tensorflow", "keras"), repos="https://cran.rstudio.com/")'
  # Clean package files
  - rm *.deb
  - service nginx restart
